version: "3"
services:
  sleek-airflow:
    build:
      context: .
      dockerfile: Dockerfile.temp
    volumes:
      - ./airflow:/opt/airflow
      - ./workspace:/opt/workspace
    ports:
      - "8080:8080"
    networks:
      - spark-cluster
    depends_on:
      - spark-master
    command: bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow db init && (airflow scheduler & airflow webserver)"

  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    ports:
      - "8081:8080" # Web UI for Spark Master
      - "7077:7077" # Spark Master Port for worker connections
    networks:
      - spark-cluster
    volumes:
      - ./workspace:/opt/workspace

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - spark-cluster
    volumes:
      - ./workspace:/opt/workspace
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - spark-cluster
    volumes:
      - ./workspace:/opt/workspace
    depends_on:
      - spark-master

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    networks:
      - spark-cluster
    volumes:
      - minio-data:/data

volumes:
  shared-workspace:
  minio-data:

networks:
  spark-cluster:
    driver: bridge
