version: "3"
services:
  sleek-airflow:
    build:
      context: .
      dockerfile: Dockerfile.temp
    volumes:
      - ./airflow:/opt/airflow
      - ./workspace:/opt/workspace
    ports:
      - "8080:8080"
    networks:
      - airflow-spark-network
    environment:
      - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
    command: bash -c "rm -f /opt/airflow/airflow-webserver.pid && airflow db init && (airflow scheduler & airflow webserver)"
  spark-master:
    image: andreper/spark-master:3.0.0
    container_name: spark-master
    ports:
      - 8081:8080
      - 7077:7077
    networks:
      - airflow-spark-network
    volumes:
      - ./workspace:/opt/workspace
  spark-worker-1:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8082:8081
    networks:
      - airflow-spark-network
    volumes:
      - ./workspace:/opt/workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: andreper/spark-worker:3.0.0
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8083:8081
    networks:
      - airflow-spark-network
    volumes:
      - ./workspace:/opt/workspace
    depends_on:
      - spark-master

volumes:
  shared-workspace:

networks:
  airflow-spark-network:
    driver: bridge
