version: "3.8"

services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-server
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: "http://0.0.0.0:5000"
      BACKEND_STORE_URI: "postgresql://mlflow:mlflow@db:5432/mlflow"
      ARTIFACT_STORE_URI: "s3://mlflow-artifacts"
    volumes:
      - ./artifacts:/mlflow/artifacts
    depends_on:
      - db
      - minio

  db:
    image: postgres:13
    container_name: mlflow-db
    environment:
      POSTGRES_USER: mlflow
      POSTGRES_PASSWORD: mlflow
      POSTGRES_DB: mlflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: mlflow-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set mlflow http://minio:9000 minio minio123) do echo 'waiting for minio'; sleep 5; done;
      /usr/bin/mc mb -p mlflow/mlflow-artifacts;
      /usr/bin/mc policy set public mlflow/mlflow-artifacts;
      "
